artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion 
  mongo_uri: "mongodb+srv://Minich:Mydatabase.456@minich-data-repository.gzlkk1s.mongodb.net/?retryWrites=true&w=majority&appName=Minich-Data-Repository"
  database_name: lead_generation
  collection_name: lead_score_cleaned


data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/lead.csv
  STATUS_FILE: artifacts/data_validation/status.json 
  critical_columns:
    - "Lead Origin" 
    - "Lead Source"
    - "Do Not Email"
    - "Do Not Call"
    - "Converted"  
    - "TotalVisits"
    - "Total Time Spent on Website"
    - "Page Views Per Visit"
    - "Last Activity" 
    - "Country" 
    - "Specialization" 
    - "How did you hear about X Education" 
    - "What is your current occupation" 
    - "What matters most to you in choosing a course" 
    - "Search" 
    - "Newspaper Article" 
    - "X Education Forums" 
    - "Newspaper" 
    - "Digital Advertisement" 
    - "Through Recommendations" 
    - "Tags" 
    - "Lead Quality" 
    - "Lead Profile" 
    - "City" 
    - "Asymmetrique Activity Index" 
    - "Asymmetrique Profile Index" 
    - "Asymmetrique Activity Score"
    - "Asymmetrique Profile Score"
    - "A free copy of Mastering The Interview" 
    - "Last Notable Activity" 
  data_ranges:
    Converted:
      min: 0
      max: 1
    TotalVisits:
      min: 0
      max: 300
    Total Time Spent on Website:
      min: 0 
      max: 2500 
    Page Views Per Visit:
      min: 0
      max: 75
    Asymmetrique Activity Score:
      min: 0
      max: 100
    Asymmetrique Profile Score:
      min: 0
      max: 100

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/lead.csv
  numerical_cols:
    - 'TotalVisits'
    - 'Total Time Spent on Website'
    - 'Page Views Per Visit'
    - 'Asymmetrique Activity Score'
    - 'Asymmetrique Profile Score'
             
  categorical_cols:
    - "Lead Origin" 
    - "Lead Source"
    - "Do Not Email"
    - "Do Not Call"
    - "Last Activity" 
    - "Country" 
    - "Specialization" 
    - "How did you hear about X Education" 
    - "What is your current occupation" 
    - "What matters most to you in choosing a course" 
    - "Search" 
    - "Newspaper Article" 
    - "X Education Forums" 
    - "Newspaper" 
    - "Digital Advertisement" 
    - "Through Recommendations" 
    - "Tags" 
    - "Lead Quality" 
    - "Lead Profile" 
    - "City" 
    - "Asymmetrique Activity Index" 
    - "Asymmetrique Profile Index" 
    - "A free copy of Mastering The Interview" 
    - "Last Notable Activity" 
    
model_trainer:
  root_dir: artifacts/model_trainer
  train_features_path: artifacts/data_transformation/X_train_tensor.pt
  train_targets_path: artifacts/data_transformation/y_train_tensor.pt
  val_features_path: artifacts/data_transformation/X_val_tensor.pt
  val_targets_path: artifacts/data_transformation/y_val_tensor.pt
  val_metrics_path: artifacts/model_trainer/model-val-metric.json
  model_name: model

model_evaluation:
  root_dir: artifacts/model_evaluation
  val_features_path: artifacts/data_transformation/X_val_tensor.pt
  val_target_path: artifacts/data_transformation/y_val_tensor.pt
  model_path: artifacts/model_trainer/{model_name}_epoch_{epochs}.pt
  metric_file_name: artifacts/model_evaluation/metrics.json
  validation_metrics_path: artifacts/model_evaluation/val_metrics.txt
  model_name: model
  training_metrics_path: artifacts/model_trainer/training_metrics.json
  report_path: artifacts/model_evaluation/classification_rep.txt
  #confusion_matrix_path: artifacts/model_evaluation/confusion_matrix.png
  confusion_matrix_report: artifacts/model_evaluation/confusion_matrix_rep.txt
  #roc_auc_path: artifacts/model_evaluation/roc-auc.png
  #pr_auc_path: artifacts/model_evaluation/pr-auc.png

model_validation:
  root_dir: artifacts/model_validation
  test_feature_path: artifacts/data_transformation/X_test_tensor.pt
  test_target_path: artifacts/data_transformation/y_test_tensor.pt
  model_path: artifacts/model_trainer/{model_name}_epoch_{epochs}.pt
  model_name: model
  class_report: artifacts/model_validation/classification-report.png
  classification_report_path: artifacts/model_validation/classification_rep.txt
  conf_matrix: artifacts/model_validation/confusion-matrix.png
  roc_auc_path: artifacts/model_validation/roc-auc.png
  pr_auc_path: artifacts/model_validation/pr-auc.png
  val_metric_file_name: artifacts/model_validation/metrics.json

