artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion 
  mongo_uri: "mongodb+srv://Minich:Mydatabase.456@minich-data-repository.gzlkk1s.mongodb.net/?retryWrites=true&w=majority&appName=Minich-Data-Repository"
  database_name: lead_generation
  collection_name: lead_score_cleaned


data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/lead.csv
  STATUS_FILE: artifacts/data_validation/status.json 
  critical_columns:
    - "Lead Origin" 
    - "Lead Source"
    - "Do Not Email"
    - "Do Not Call"
    - "Converted"  
    - "TotalVisits"
    - "Total Time Spent on Website"
    - "Page Views Per Visit"
    - "Last Activity" 
    - "Country" 
    - "Specialization" 
    - "How did you hear about X Education" 
    - "What is your current occupation" 
    - "What matters most to you in choosing a course" 
    - "Search" 
    - "Newspaper Article" 
    - "X Education Forums" 
    - "Newspaper" 
    - "Digital Advertisement" 
    - "Through Recommendations" 
    - "Tags" 
    - "Lead Quality" 
    - "Lead Profile" 
    - "City" 
    - "Asymmetrique Activity Index" 
    - "Asymmetrique Profile Index" 
    - "Asymmetrique Activity Score"
    - "Asymmetrique Profile Score"
    - "A free copy of Mastering The Interview" 
    - "Last Notable Activity" 
  data_ranges:
    Converted:
      min: 0
      max: 1
    TotalVisits:
      min: 0
      max: 300
    Total Time Spent on Website:
      min: 0 
      max: 2500 
    Page Views Per Visit:
      min: 0
      max: 75
    Asymmetrique Activity Score:
      min: 0
      max: 100
    Asymmetrique Profile Score:
      min: 0
      max: 100

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/lead.csv
  numerical_cols:
    - 'TotalVisits'
    - 'Total Time Spent on Website'
    - 'Page Views Per Visit'
    - 'Asymmetrique Activity Score'
    - 'Asymmetrique Profile Score'
             
  categorical_cols:
    - "Lead Origin" 
    - "Lead Source"
    - "Do Not Email"
    - "Do Not Call"
    - "Last Activity" 
    - "Country" 
    - "Specialization" 
    - "How did you hear about X Education" 
    - "What is your current occupation" 
    - "What matters most to you in choosing a course" 
    - "Search" 
    - "Newspaper Article" 
    - "X Education Forums" 
    - "Newspaper" 
    - "Digital Advertisement" 
    - "Through Recommendations" 
    - "Tags" 
    - "Lead Quality" 
    - "Lead Profile" 
    - "City" 
    - "Asymmetrique Activity Index" 
    - "Asymmetrique Profile Index" 
    - "A free copy of Mastering The Interview" 
    - "Last Notable Activity" 
    
model_trainer:
  root_dir: artifacts/model_trainer
  train_features_path: artifacts/data_transformation/X_train_tensor.pt
  train_targets_path: artifacts/data_transformation/y_train_tensor.pt
  model_name: model.pt